language: php
dist: trusty

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  allow_failures:
    - php: 7.4
      dist: trusty

before_script:
  - echo 'xdebug.max_nesting_level=999999' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer install

script:
  - vendor/bin/phpunit --testsuite travis-ci
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
